33 tcp and kcp protocol
n-hop/oasis pull request #34
Opened 2024-08-16 08:46 UTC by wandou2018

2024-08-16 08:51 UTC, penglei0 commented on src/protosuites/default_protocol.py
> +class DefaultProtocol(IProtoSuite, IProtoInfo):
可以删掉，TCPProtocol就是default

2024-08-19 04:49 UTC, penglei0 requested changes

2024-08-19 04:49 UTC, penglei0 commented on src/protosuites/proto.py
> +    def start(self, network: 'INetwork', client_host:int, server_host:int):  # type: ignore
这样改接口显然不合适啊，并不是每个协议都有client/server的概念。应该用ProtoConfig.hosts去实现

2024-08-19 04:49 UTC, penglei0 commented on src/run_test.py
> +            cs = CSProtocol(KCPProtocol(kcp_client_cfg), KCPProtocol(kcp_server_cfg))
```python
cs_config = ProtoConfig()
cs_config.hosts = [0,6]
cs = CSProtocol(cs_config, KCPProtocol(kcp_client_cfg), KCPProtocol(kcp_server_cfg))
```

2024-08-19 04:49 UTC, penglei0 commented on src/interfaces/network.py
> -            proto.start(self)
```python
if not proto.is_distributed():
  proto_config = proto.get_config()
  proto_config.hosts = [test.config.client_host, test.config.server_host]
```
add is_distributed to IProtoSuite, default return True; but for CSProtocol, it return False.

2024-08-19 04:49 UTC, penglei0 commented on src/protosuites/kcp_protocol.py
> +            args = (f'-r {recver_ip}:4000'
这些args 应该和path（/root/kcp/client_linux_amd64）一样，都是放在protocolConfig里面

2024-08-19 06:46 UTC, wandou2018 commented
![image](https://github.com/user-attachments/assets/5d253c92-bebd-4af6-99e1-de8ea0c59c51)

2024-08-19 06:59 UTC, penglei0 commented
> ![image](https://private-user-images.githubusercontent.com/119300977/359005335-5d253c92-bebd-4af6-99e1-de8ea0c59c51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNTA5OTQsIm5iZiI6MTcyNDA1MDY5NCwicGF0aCI6Ii8xMTkzMDA5NzcvMzU5MDA1MzM1LTVkMjUzYzkyLWJlYmQtNGFmNi05OWUxLWRlOGVhMGM1OWM1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQwNjU4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzE4M2U4MDA1NDc5MzVhYTJjMzU1ZTFjYmU1MWU4YTdhN2FiNTAxOTNlNzk5ZWJlZDM3OWI1ZGI4MzI4OTFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8rG8XTwuTPSIYdRKENM4mH2noI-v994eu9sFIVhcz98)

差一个protocol name

2024-08-19 09:05 UTC, penglei0 commented on src/interfaces/network.py
> +                    proto.get_config().hosts = [test.config.client_host, test.config.server_host]
不是distributed的协议，才需要配置client/server host.

2024-08-19 09:07 UTC, penglei0 commented on src/protosuites/cs_protocol.py
> +        return True
协议有两种：分布式的（distributed）；非分布式（即client-server mode）

2024-08-19 09:23 UTC, wandou2018 commented
![image](https://github.com/user-attachments/assets/e86c1605-05f7-4710-8515-4d02582c54bf)

2024-08-19 09:33 UTC, penglei0 commented
> ![image](https://private-user-images.githubusercontent.com/119300977/359051513-e86c1605-05f7-4710-8515-4d02582c54bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNjAyNTYsIm5iZiI6MTcyNDA1OTk1NiwicGF0aCI6Ii8xMTkzMDA5NzcvMzU5MDUxNTEzLWU4NmMxNjA1LTA1ZjctNDcxMC04NTE1LTRkMDI1ODJjNTRiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQwOTMyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTA2ZjYwMzEzYjg4ZDliYTk3MDc0MjQ3ZDljZmMxMzFjOTM3ODgyNGIwODE0YjM5NjhhZTViN2Q0MDg3OTZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4OBREParBLIJyoumENzGrk77FmIo8PjsLK0RB8vR2xg)

@wandou2018 Protocol name uses upper case

2024-08-19 10:09 UTC, penglei0 approved these changes

2024-08-19 10:10 UTC, merged